# -*- coding: utf-8 -*-
"""LuisAlvarez_Mineria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpCvC7zUExpwRpCuQPNNiIW5NAEGwne1

#**EJERCICIO 1 MINERIA DE DATOS**

- Catedra: Mineria de Datos
- Periodo: 2025C
- Realizado por: Luis Alvarez
- Docente: Daniel Carrizo

**Descripción del Proyecto**

Este proyecto realiza un análisis exhaustivo de los datos del departamento de Recursos Humanos de una empresa de tecnología, con el objetivo de identificar patrones, tendencias y áreas de oportunidad en la gestión del talento humano.

# **1: Configuración Inicial y Carga de Datos**

Se estableció el entorno analítico importando librerías especializadas para el procesamiento de datos. Pandas y NumPy se utilizaron para la manipulación de datos tabulares y cálculos numéricos, mientras que Matplotlib y Seaborn permitieron la visualización de resultados. Para el análisis estadístico se incluyeron funciones de Scipy, y la carga del dataset se realizó mediante files.upload() de Google Colab, cargando el archivo Excel en un DataFrame de pandas con pd.read_excel('dataset_exercise.xlsx') para su posterior procesamiento.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import spearmanr, mannwhitneyu, chi2_contingency
from google.colab import files

# Cargar el dataset
archivo = files.upload()
df = pd.read_excel('dataset_exercise.xlsx')

"""# **2. Diagnóstico Inicial del Dataset**
Se realizó un análisis exploratorio inicial del dataset para comprender su estructura básica. El diagnóstico incluyó la verificación de dimensiones, revelando la cantidad total de filas y columnas disponibles para el análisis. Posteriormente, se examinó la tipología de datos mediante df.info(), identificando la distribución de variables categóricas, numéricas y de fecha, lo que permitió establecer una base sólida para las fases subsiguientes de limpieza y transformación de datos.
"""

# Información general del dataset
print("=== INFORMACIÓN INICIAL ===")
print(f"Dimensiones: {df.shape}")
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")
print("\n=== TIPOS DE DATOS ===")
df.info()

"""#2.1 Análisis de Valores Faltantes
Se implementó una evaluación exhaustiva de los valores nulos presentes en el dataset, calculando tanto la frecuencia absoluta como el porcentaje relativo de valores faltantes por columna. Este diagnóstico permitió identificar las variables que requerían estrategias de imputación específicas, estableciendo una línea base cuantitativa para priorizar las intervenciones de limpieza de datos durante las fases posteriores del proceso.


"""

print("\n=== VALORES NULOS POR COLUMNA ===")
null_sum = df.isnull().sum()
null_pct = (df.isnull().sum() / len(df)) * 100
null_info = pd.DataFrame({'Valores_Nulos': null_sum, 'Porcentaje': null_pct})
print(null_info[null_info['Valores_Nulos'] > 0])

"""# **3. Proceso de Limpieza y Transformación de Datos**
Se ejecutó un proceso comprehensivo de limpieza y transformación de datos que incluyó múltiples etapas para garantizar la calidad, integridad y consistencia del dataset. Este proceso sistemático abordó problemáticas específicas de valores faltantes, estandarización de formatos y optimización de la estructura de datos, permitiendo preparar la base de información para análisis posteriores. Las intervenciones realizadas se fundamentaron en relaciones lógicas entre variables y mejores prácticas de gestión de datos, asegurando la preservación de la información original mientras se maximizaba la utilidad analítica del conjunto de datos resultante.

#3.1 Limpieza de Registros Duplicados
Se ejecutó un proceso de detección y eliminación de filas duplicadas para garantizar la calidad e integridad del dataset. Mediante la función df.duplicated().sum() se identificó la cantidad de registros repetidos, mostrando ejemplos representativos cuando existían duplicados. Posteriormente, se aplicó df.drop_duplicates() para eliminar estas repeticiones, registrando las métricas antes y después de la depuración. Este procedimiento aseguró la unicidad de los registros para análisis posteriores, manteniendo solo la información única y relevante.
"""

# === Eliminar filas duplicadas ===

print("🔍 BUSCANDO Y ELIMINANDO DUPLICADOS")
print("=" * 40)

# Ver duplicados antes
duplicados_antes = df.duplicated().sum()
print(f"Filas duplicadas encontradas: {duplicados_antes}")

if duplicados_antes > 0:
    # Mostrar algunas filas duplicadas
    print(f"\n📋 Mostrando {min(3, duplicados_antes)} filas duplicadas:")
    duplicados = df[df.duplicated(keep=False)]
    print(duplicados.head(3))

    # Eliminar duplicados
    df = df.drop_duplicates()

    # Ver resultados
    filas_antes = len(df) + duplicados_antes
    filas_despues = len(df)
    eliminadas = filas_antes - filas_despues

    print(f"\n✅ Duplicados eliminados: {eliminadas} filas")
    print(f"📊 Filas antes: {filas_antes}")
    print(f"📊 Filas después: {filas_despues}")
else:
    print("✅ No se encontraron filas duplicadas")

print(f"📊 Dataset final: {len(df)} filas x {len(df.columns)} columnas")

"""#3.2 Imputación de Valores en MarriedID
Se implementó una estrategia de completado para la variable MarriedID utilizando la información disponible en MaritalDesc. El proceso consistió en identificar los valores nulos en MarriedID que contaban con datos correspondientes en MaritalDesc, aplicando luego una regla de mapeo donde se asignó valor 1 para el estado "married" y 0 para los demás estados civiles. Esta imputación permitió recuperar registros manteniendo la consistencia lógica entre las variables relacionadas, reduciendo significativamente los valores faltantes en esta columna.
"""

print("=== MarriedID ===")

# Verificar columnas
if 'MarriedID' in df.columns and 'MaritalDesc' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['MarriedID'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['MarriedID'].isna() & df['MaritalDesc'].notna()]

    # Aplicar regla simple
    for index in filas_a_rellenar.index:
        estado_marital = str(df.loc[index, 'MaritalDesc']).strip().lower()
        df.loc[index, 'MarriedID'] = 1 if estado_marital == 'married' else 0

    nulos_finales = df['MarriedID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")

else:
    print("❌ No se encontraron las columnas necesarias")

"""#3.3 Imputación de Valores en GenderID
Se ejecutó el proceso de imputación para la variable GenderID basándose en la información de la columna Sex. Tras identificar los valores faltantes en GenderID que disponían de datos correspondientes en Sex, se aplicó un mapeo directo donde el valor 'M' se transformó a 1 y cualquier otro valor se asignó a 0. Esta estandarización permitió homogenizar la codificación de género en el dataset, manteniendo la coherencia entre las representaciones textual y numérica de esta variable demográfica.
"""

print("=== Gender ===")

# Verificar columnas
if 'GenderID' in df.columns and 'Sex' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['GenderID'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['GenderID'].isna() & df['Sex'].notna()]

    # Aplicar regla simple CORREGIDA
    for index in filas_a_rellenar.index:
        sexo = str(df.loc[index, 'Sex']).strip().upper()
        df.loc[index, 'GenderID'] = 1 if sexo == 'M' else 0

    nulos_finales = df['GenderID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")

else:
    print("❌ No se encontraron las columnas necesarias")

"""# 3.4 Imputación de Valores en MaritalStatusID
Se implementó un sistema de mapeo comprehensivo para transformar las descripciones textuales de estado civil en códigos numéricos estandarizados en MaritalStatusID. El proceso asignó valores específicos a cada categoría: 0 para "single", 1 para "married", 2 para "divorced", 3 para "separated" y 4 para "widowed". Esta codificación permitió no solo completar los valores faltantes sino también crear una variable categórica ordinal que facilitaría posteriores análisis estadísticos sobre el impacto del estado civil en variables laborales.
"""

print("=== MaritalStatusID ===")

if 'MaritalStatusID' in df.columns and 'MaritalDesc' in df.columns:

    nulos_iniciales = df['MaritalStatusID'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['MaritalStatusID'].isna() & df['MaritalDesc'].notna()]

    print(f"Filas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar regla de mapeo
    for index in filas_a_rellenar.index:
        estado_marital = str(df.loc[index, 'MaritalDesc']).strip().lower()

        # Mapear texto a código numérico
        if estado_marital == 'single':
            df.loc[index, 'MaritalStatusID'] = 0
        elif estado_marital == 'married':
            df.loc[index, 'MaritalStatusID'] = 1
        elif estado_marital == 'divorced':
            df.loc[index, 'MaritalStatusID'] = 2
        elif estado_marital == 'separated':
            df.loc[index, 'MaritalStatusID'] = 3
        elif estado_marital == 'widowed':
            df.loc[index, 'MaritalStatusID'] = 4
        else:
            # Por si hay valores inesperados
            print(f"Valor inesperado en MaritalDesc: {estado_marital}")
            df.loc[index, 'MaritalStatusID'] = None

    nulos_finales = df['MaritalStatusID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final:")
    print(df['MaritalStatusID'].value_counts().sort_index())

else:
    print("❌ No se encontraron las columnas necesarias")

"""#3.5
 Imputación de Valores en EmpStatusID
Se implementó un proceso de mapeo sistemático para completar los valores faltantes en EmpStatusID utilizando la información disponible en EmploymentStatus. La estrategia consistió en identificar coincidencias textuales específicas: se asignó código 1 para "active", 5 para "voluntarily terminated", 4 para "terminated for cause" y 2 para estados que contenían "leave" en su descripción. Este enfoque permitió estandarizar la codificación numérica de los estados laborales manteniendo la correspondencia exacta con las descripciones textuales originales, logrando una reducción significativa de valores nulos en esta variable.
"""

print("=== EmpStatusID ===")

if 'EmpStatusID' in df.columns and 'EmploymentStatus' in df.columns:

    nulos_iniciales = df['EmpStatusID'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['EmpStatusID'].isna() & df['EmploymentStatus'].notna()]

    print(f"Filas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar regla de mapeo
    for index in filas_a_rellenar.index:
        estado_empleo = str(df.loc[index, 'EmploymentStatus']).strip().lower()

        # Mapear texto a código numérico
        if estado_empleo == 'active':
            df.loc[index, 'EmpStatusID'] = 1
        elif estado_empleo == 'voluntarily terminated':
            df.loc[index, 'EmpStatusID'] = 5
        elif estado_empleo == 'terminated for cause':
            df.loc[index, 'EmpStatusID'] = 4
        elif 'leave' in estado_empleo:  # Por si hay tipos de licencia
            df.loc[index, 'EmpStatusID'] = 2
        else:
            # Por si hay valores inesperados
            print(f"Valor inesperado en EmploymentStatus: {estado_empleo}")
            df.loc[index, 'EmpStatusID'] = None

    # Resultados
    nulos_finales = df['EmpStatusID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final:")
    print(df['EmpStatusID'].value_counts().sort_index())

else:
    print("❌ No se encontraron las columnas necesarias")

"""#3.6 Imputación de Valores en EmploymentStatus
Se ejecutó un proceso de mapeo inverso para completar los valores faltantes en EmploymentStatus utilizando la información disponible en EmpStatusID. La estrategia implementó una correspondencia bidireccional donde cada código numérico se tradujo a su descripción textual equivalente: 1 a "Active", 2 a "Leave of Absence", 4 a "Terminated for Cause" y 5 a "Voluntarily Terminated". Este enfoque de retroalimentación entre variables relacionadas permitió mantener la integridad referencial del dataset, asegurando coherencia entre las representaciones numéricas y textuales de los estados laborales.

"""

print("=== EmploymentStatus (desde EmpStatusID) ===")

if 'EmploymentStatus' in df.columns and 'EmpStatusID' in df.columns:

    nulos_iniciales = df['EmploymentStatus'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['EmploymentStatus'].isna() & df['EmpStatusID'].notna()]

    print(f"Filas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar regla de mapeo INVERSA
    for index in filas_a_rellenar.index:
        estado_id = df.loc[index, 'EmpStatusID']

        # Mapear código numérico a texto (INVERSO)
        if estado_id == 1:
            df.loc[index, 'EmploymentStatus'] = 'Active'
        elif estado_id == 2:
            df.loc[index, 'EmploymentStatus'] = 'Leave of Absence'
        elif estado_id == 3:
            df.loc[index, 'EmploymentStatus'] = 'Active'  # Según tu caso especial
        elif estado_id == 4:
            df.loc[index, 'EmploymentStatus'] = 'Terminated for Cause'
        elif estado_id == 5:
            df.loc[index, 'EmploymentStatus'] = 'Voluntarily Terminated'
        else:
            # Por si hay valores inesperados
            print(f"Valor inesperado en EmpStatusID: {estado_id}")
            df.loc[index, 'EmploymentStatus'] = None

    # Resultados
    nulos_finales = df['EmploymentStatus'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final:")
    print(df['EmploymentStatus'].value_counts())

else:
    print("❌ No se encontraron las columnas necesarias")

"""#3.7 Imputación de Valores en DeptID
Se implementó un sistema de codificación para completar los valores faltantes en DeptID utilizando la información disponible en Department. La estrategia consistió en mapear cada nombre de departamento a su identificador numérico correspondiente: 1 para "admin offices", 2 para departamentos ejecutivos, 3 para "it/is", 4 para "software engineering", 5 para "production" y 6 para "sales". Este proceso de estandarización permitió crear una correspondencia unívoca entre las denominaciones textuales de los departamentos y sus códigos identificadores, facilitando el análisis segmentado por áreas organizacionales.


"""

print("=== DeptID ===")

# Verificar columnas CORREGIDAS
if 'DeptID' in df.columns and 'Department' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['DeptID'].isna().sum()

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['DeptID'].isna() & df['Department'].notna()]

    print(f"Filas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar regla de mapeo
    for index in filas_a_rellenar.index:
        departamento = str(df.loc[index, 'Department']).strip().lower()

        # Mapear departamento a código numérico
        if departamento == 'admin offices':
            df.loc[index, 'DeptID'] = 1
        elif 'executive' in departamento:
            df.loc[index, 'DeptID'] = 2
        elif departamento == 'it/is':
            df.loc[index, 'DeptID'] = 3
        elif departamento == 'software engineering':
            df.loc[index, 'DeptID'] = 4
        elif departamento == 'production':
            df.loc[index, 'DeptID'] = 5
        elif departamento == 'sales':
            df.loc[index, 'DeptID'] = 6

        else:
            # Por si hay valores inesperados
            print(f"Valor inesperado en Department: {departamento}")
            df.loc[index, 'DeptID'] = None

    # Resultados
    nulos_finales = df['DeptID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final:")
    print(df['DeptID'].value_counts().sort_index())

else:
    print("❌ No se encontraron las columnas DeptID o Department")

"""#3.8 Imputación de Valores en PerfScoreID
Se implementó un sistema de mapeo por coincidencias parciales para completar los valores faltantes en PerfScoreID utilizando la información disponible en PerformanceScore. La estrategia asignó códigos numéricos basados en palabras clave específicas: 4 para evaluaciones que contenían "exceed", 3 para "fully meet", 2 para "need" o "improvement", y 1 para "pip". Este enfoque flexible permitió manejar variaciones en la formulación de las calificaciones de desempeño mientras se mantenía una escala numérica estandarizada para facilitar el análisis comparativo del rendimiento laboral.
"""

print("=== PerfScoreID ===")

# Verificar columnas CORREGIDAS
if 'PerfScoreID' in df.columns and 'PerformanceScore' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['PerfScoreID'].isna().sum()

    # Filtrar filas que necesitan rellenarse (CORREGIDO)
    filas_a_rellenar = df[df['PerfScoreID'].isna() & df['PerformanceScore'].notna()]

    print(f"Filas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar regla de mapeo CORREGIDA
    for index in filas_a_rellenar.index:
        puntuacion = str(df.loc[index, 'PerformanceScore']).strip().lower()

        # Mapear PerformanceScore a código numérico (CORREGIDO)
        if 'exceed' in puntuacion:
            df.loc[index, 'PerfScoreID'] = 4
        elif 'fully meet' in puntuacion:
            df.loc[index, 'PerfScoreID'] = 3
        elif 'need' in puntuacion or 'improvement' in puntuacion:
            df.loc[index, 'PerfScoreID'] = 2
        elif 'pip' in puntuacion:
            df.loc[index, 'PerfScoreID'] = 1
        else:
            # Por si hay valores inesperados
            print(f"Valor inesperado en PerformanceScore: {puntuacion}")
            df.loc[index, 'PerfScoreID'] = None

    # Resultados
    nulos_finales = df['PerfScoreID'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final:")
    print(df['PerfScoreID'].value_counts().sort_index())

else:
    print("❌ No se encontraron las columnas PerfScoreID o PerformanceScore")

"""#3.9 Completado de Salarios por Media Departamental
Se implementó una estrategia de completado para los valores faltantes en Salary utilizando promedios departamentales. El proceso consistió en calcular la media salarial para cada departamento con datos existentes, identificando posteriormente los registros con salarios nulos que contaban con información departamental válida. Para cada empleado con salario faltante, se asignó el promedio correspondiente a su departamento, asegurando así una imputación contextualmente relevante que mantiene la coherencia con la estructura salarial de cada área organizacional.
"""

print("=== Salary ===")

if 'Salary' in df.columns and 'Department' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['Salary'].isna().sum()

    # Calcular la media de salario por departamento (excluyendo nulos)
    media_por_departamento = df.groupby('Department')['Salary'].mean()

    print("Medias de salario por departamento:")
    for dept, media in media_por_departamento.items():
        print(f"  {dept}: ${media:,.2f}")

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['Salary'].isna() & df['Department'].notna()]

    print(f"\nFilas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar relleno con media del departamento
    for index in filas_a_rellenar.index:
        departamento = df.loc[index, 'Department']
        media_departamento = media_por_departamento.get(departamento)

        if pd.notna(media_departamento):
            df.loc[index, 'Salary'] = media_departamento
            print(f"  ✅ {departamento}: ${media_departamento:,.2f}")
        else:
            print(f"  ❌ No se pudo calcular media para: {departamento}")

    # Resultados
    nulos_finales = df['Salary'].isna().sum()
    rellenados = nulos_iniciales - nulos_finales

    print(f"\n✅ Se rellenaron {rellenados} valores de Salary")
    print(f"   Nulos: {nulos_iniciales} → {nulos_finales}")

else:
    print("❌ No se encontraron las columnas Salary o Department")

"""#3.10 Estandarización y Completado de HispanicLatino
Se ejecutó un proceso de normalización y completado para la variable HispanicLatino que incluyó dos fases principales. Primero, se estandarizaron todos los valores existentes mediante un mapeo comprehensivo que unificó las variaciones textuales ("si", "sí", "yes", "y") en "Sí" y ("no", "not") en "No". Segundo, se completaron los valores nulos asignando la categoría "Desconocido" para mantener la transparencia en el tratamiento de datos faltantes. Este enfoque permitió homogenizar la variable mientras se preservaba la trazabilidad de la información original.
"""

print("=== HispanicLatino ===")

if 'HispanicLatino' in df.columns:

    # Contar nulos iniciales
    nulos_iniciales = df['HispanicLatino'].isna().sum()

    # Mostrar valores únicos antes de limpiar
    print("Valores únicos antes de limpiar:")
    print(df['HispanicLatino'].value_counts(dropna=False))

    # Primero: Estandarizar los valores existentes (No, NO, no → "No", Si, SI, si → "Sí")
    for index in df[df['HispanicLatino'].notna()].index:
        valor_actual = str(df.loc[index, 'HispanicLatino']).strip()

        # Estandarizar a "Sí" o "No"
        if valor_actual.lower() in ['si', 'sí', 'yes', 'y']:
            df.loc[index, 'HispanicLatino'] = 'Sí'
        elif valor_actual.lower() in ['no', 'not']:
            df.loc[index, 'HispanicLatino'] = 'No'
        # Si ya está bien escrito, mantenerlo
        elif valor_actual in ['Sí', 'No']:
            pass
        else:
            # Para cualquier otro valor, convertirlo a "No" por seguridad
            df.loc[index, 'HispanicLatino'] = 'No'
            print(f"  Valor convertido: '{valor_actual}' → 'No'")

    # Segundo: Rellenar nulos con "Desconocido"
    df['HispanicLatino'] = df['HispanicLatino'].fillna('Desconocido')

    # Resultados
    nulos_finales = df['HispanicLatino'].isna().sum()
    rellenados = nulos_iniciales

    print(f"\n✅ Se estandarizaron valores y rellenaron {rellenados} nulos")
    print(f"   Nulos: {nulos_iniciales} → {nulos_finales}")
    print(f"\nValores únicos después de limpiar:")
    print(df['HispanicLatino'].value_counts())

else:
    print("❌ No se encontró la columna HispanicLatino")

"""#3.11 Completado de ManagerID mediante Mapeo Relacional
Se implementó una estrategia de completado para ManagerID basada en relaciones existentes entre ManagerName y ManagerID. El proceso inició con la construcción de un diccionario de mapeo que capturó todas las asociaciones válidas entre nombres de managers y sus identificadores numéricos. Posteriormente, se utilizó este mapeo para asignar los IDs correspondientes a los registros con valores faltantes, asegurando la consistencia en la identificación de supervisores a lo largo del dataset. Este enfoque relacional permitió mantener la integridad referencial de la estructura organizacional.
"""

print("=== ManagerID ===")

if 'ManagerID' in df.columns and 'ManagerName' in df.columns:

    nulos_iniciales = df['ManagerID'].isna().sum()

    # Primero: crear un mapeo único de ManagerName a ManagerID
    mapeo_manager = {}

    # Buscar relaciones existentes entre ManagerName y ManagerID
    managers_con_id = df[df['ManagerID'].notna() & df['ManagerName'].notna()]

    for _, fila in managers_con_id.iterrows():
        nombre = fila['ManagerName']
        id_valor = fila['ManagerID']
        if pd.notna(nombre) and pd.notna(id_valor):
            mapeo_manager[nombre] = id_valor

    print(f"Se encontraron {len(mapeo_manager)} mapeos de Manager existentes:")
    for nombre, id_valor in mapeo_manager.items():
        print(f"  {nombre} → {id_valor}")

    # Filtrar filas que necesitan rellenarse
    filas_a_rellenar = df[df['ManagerID'].isna() & df['ManagerName'].notna()]

    print(f"\nFilas a rellenar: {len(filas_a_rellenar)}")

    # Aplicar relleno usando el mapeo
    rellenados = 0
    for index in filas_a_rellenar.index:
        nombre_manager = df.loc[index, 'ManagerName']

        if nombre_manager in mapeo_manager:
            df.loc[index, 'ManagerID'] = mapeo_manager[nombre_manager]
            rellenados += 1
            print(f"  ✅ {nombre_manager} → {mapeo_manager[nombre_manager]}")
        else:
            print(f"  ❌ No se encontró ID para: {nombre_manager}")

    # Resultados
    nulos_finales = df['ManagerID'].isna().sum()

    print(f"\n✅ Se rellenaron {rellenados} valores")
    print(f"   De {nulos_iniciales} nulos a {nulos_finales} nulos")
    print(f"   Distribución final de ManagerID:")
    print(df['ManagerID'].value_counts().sort_index())

else:
    print("❌ No se encontraron las columnas necesarias")

"""#3.12 Estandarización de Tipos de Datos y Análisis Final de Nulos
Se ejecutó un proceso de optimización de tipos de datos que incluyó tres categorías principales: conversión de variables textuales a tipo categórico para mejorar el rendimiento, transformación de identificadores numéricos a formato Int64, y estandarización de fechas a formato datetime. Paralelamente, se realizó un análisis comparativo de valores nulos antes y después de las conversiones, generando un reporte detallado que cuantificó tanto la frecuencia absoluta como el porcentaje relativo de valores faltantes por columna. Este proceso permitió optimizar la estructura del dataset para análisis posteriores mientras se documentaba el estado final de completitud de los datos.
"""

# === Garantizar tipos de datos ===

# Columnas a convertir
categoricas = ['Position','State','Sex','MaritalDesc','CitizenDesc','RaceDesc',
               'EmploymentStatus','Department','RecruitmentSource','PerformanceScore','HispanicLatino']
columnas_id = ['MarriedID','MaritalStatusID','GenderID','EmpStatusID','DeptID','PerfScoreID','ManagerID']
columnas_fecha = ['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReviewDate']

# 1) Resumen inicial de nulos
print("Nulos antes de convertir tipos:")
print(df.isnull().sum())

# 2) Convertir columnas categóricas
print("\nConvirtiendo columnas categóricas...")
for col in categoricas:
    if col in df.columns:
        df[col] = df[col].astype('category')
        print(f"✓ {col} convertida a category")

# 3) Convertir columnas ID
print("\nConvirtiendo columnas ID...")
for col in columnas_id:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
        print(f"✓ {col} convertida a Int64")

# 4) Convertir fechas
print("\nConvirtiendo fechas...")
for col in columnas_fecha:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
        print(f"✓ {col} convertida a datetime")

# 5) Resumen final de nulos
print("\n" + "="*50)
print("RESUMEN FINAL DE VALORES NULOS:")
print("="*50)

nulos = df.isnull().sum()
porcentaje = (nulos / len(df) * 100).round(2)

resumen = pd.DataFrame({
    'Valores_Nulos': nulos,
    'Porcentaje_Nulos': porcentaje
})

# Mostrar solo columnas con nulos
resumen_con_nulos = resumen[resumen['Valores_Nulos'] > 0].sort_values('Valores_Nulos', ascending=False)
print(resumen_con_nulos)

"""#3.13 Eliminación de Columnas Redundantes
Se implementó un proceso de depuración para eliminar columnas redundantes que representaban información duplicada en formatos diferentes. Mediante un mapeo predefinido, se identificaron pares de variables donde los identificadores numéricos (IDs) tenían equivalentes textuales descriptivos completos. Se procedió a eliminar sistemáticamente las columnas de IDs numéricos, conservando únicamente las versiones textuales que ofrecen mayor legibilidad y contexto para el análisis. Esta optimización redujo la dimensionalidad del dataset manteniendo toda la información relevante y mejorando la eficiencia en el procesamiento posterior.


"""

# === Eliminar redundancia ===
# Columnas a eliminar (IDs numéricos) y sus equivalentes en texto
columnas_redundantes = {
    'GenderID': 'Sex',
    'MaritalStatusID': 'MaritalDesc',
    'MarriedID': 'MaritalDesc',
    'EmpStatusID': 'EmploymentStatus',
    'PerfScoreID': 'PerformanceScore',
    'DeptID': 'Department',
    'ManagerID': 'ManagerName'
}

print("🗑️  ELIMINANDO COLUMNAS REDUNDANTES")
print("=" * 40)

# Eliminar columnas redundantes
columnas_eliminadas = []
for columna_id, columna_texto in columnas_redundantes.items():
    if columna_id in df.columns:
        df = df.drop(columns=[columna_id])
        columnas_eliminadas.append(columna_id)
        print(f"❌ Eliminada: {columna_id} (redundante con {columna_texto})")

print(f"\n✅ Se eliminaron {len(columnas_eliminadas)} columnas redundantes")

""" # **4. ¿Existe alguna relación entre el departamento para la que trabaja una persona y su puntuación de rendimiento?**"""

print("=== PREGUNTA 1: ¿Existe relación entre departamento y rendimiento? ===")

# Crear tabla de contingencia
contingency_table = pd.crosstab(df['Department'], df['PerformanceScore'])

# Prueba de Chi-cuadrado
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(f"Chi² = {chi2:.4f}, p-value = {p_value:.4f}")

if p_value < 0.05:
    print("✅ CONCLUSIÓN: Existe relación significativa")
else:
    print("❌ CONCLUSIÓN: No existe relación significativa")

# Gráfica simple de barras
plt.figure(figsize=(10, 6))
contingency_table.plot(kind='bar', alpha=0.8)
plt.title('Rendimiento por Departamento')
plt.xlabel('Departamento')
plt.ylabel('Cantidad de Empleados')
plt.legend(title='Rendimiento')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""El análisis estadístico mediante prueba de Chi-cuadrado (χ² = 13.7255, p = 0.5464) determina que no existe relación significativa entre el departamento de trabajo y el rendimiento de los empleados. El valor p superior a 0.05 indica que las diferencias observadas en las puntuaciones de desempeño entre departamentos son atribuibles al azar.

Este resultado sugiere que el sistema de evaluación se aplica consistentemente en toda la organización, manteniendo estándares uniformes independientemente del área funcional. La falta de asociación señala que el rendimiento está más influenciado por factores individuales que por la pertenencia departamental, reflejando una cultura organizacional cohesionada con criterios de desempeño alineados corporativamente.

# **5. ¿Cuál es el perfil general de diversidad de la organización?**
"""

print("\n=== PREGUNTA 2: ¿Cuál es el perfil general de diversidad? ===")

plt.figure(figsize=(14, 10))

# Subplot 1: Histograma de razas/etnias
plt.subplot(2, 2, 1)
race_counts = df['RaceDesc'].value_counts()
colors = plt.cm.Set3(np.linspace(0, 1, len(race_counts)))

bars = plt.bar(race_counts.index, race_counts.values, color=colors, edgecolor='black', alpha=0.8)
plt.title('Distribución por Raza/Etnia', fontsize=12, fontweight='bold')
plt.xlabel('Raza/Etnia')
plt.ylabel('Número de Empleados')
plt.xticks(rotation=45, ha='right')

# Añadir valores en las barras
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom', fontsize=9)

# Subplot 2: Género (mejorado)
plt.subplot(2, 2, 2)
gender_counts = df['Sex'].value_counts()
gender_colors = ['lightblue', 'lightpink']
plt.pie(gender_counts.values, labels=gender_counts.index, autopct='%1.1f%%',
        colors=gender_colors, startangle=90, textprops={'fontsize': 10})
plt.title('Distribución por Género', fontsize=12, fontweight='bold')

# Subplot 3: Hispanic/Latino (mejorado)
plt.subplot(2, 2, 3)
hispanic_counts = df['HispanicLatino'].value_counts()
hispanic_colors = ['lightgreen', 'lightcoral']
plt.bar(hispanic_counts.index, hispanic_counts.values, color=hispanic_colors,
        edgecolor='black', alpha=0.8)
plt.title('Distribución Hispanic/Latino', fontsize=12, fontweight='bold')
plt.ylabel('Número de Empleados')

# Añadir valores en las barras
for i, count in enumerate(hispanic_counts.values):
    plt.text(i, count + 0.1, str(count), ha='center', va='bottom', fontweight='bold')

# Subplot 4: Estado civil (mejorado)
plt.subplot(2, 2, 4)
marital_counts = df['MaritalDesc'].value_counts().head(5)
plt.bar(marital_counts.index, marital_counts.values, color='skyblue',
        edgecolor='black', alpha=0.8)
plt.title('Distribución por Estado Civil', fontsize=12, fontweight='bold')
plt.ylabel('Número de Empleados')
plt.xticks(rotation=45, ha='right')

# Añadir valores en las barras
for i, count in enumerate(marital_counts.values):
    plt.text(i, count + 0.1, str(count), ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

# Estadísticas numéricas
print("\n--- ESTADÍSTICAS DE DIVERSIDAD ---")
print(f"Total empleados: {len(df)}")
print(f"Distribución por género:")
print(df['Sex'].value_counts(normalize=True).round(3))
print(f"\nGrupos raciales representados: {df['RaceDesc'].nunique()}")
print(f"Departamentos representados: {df['Department'].nunique()}")

# Tabla detallada de diversidad racial
print("\n--- DISTRIBUCIÓN RACIAL DETALLADA ---")
racial_breakdown = df['RaceDesc'].value_counts()
for race, count in racial_breakdown.items():
    percentage = (count / len(df)) * 100
    print(f"{race}: {count} empleados ({percentage:.1f}%)")

"""El perfil de diversidad de la organización revela un panorama con importantes áreas de oportunidad. Si bien cuentas con un balance saludable en cuanto a género, con una distribución 56.6% femenino y 43.4% masculino, la composición étnica presenta desequilibrios significativos que requieren atención inmediata. La sobrerrepresentación de empleados blancos (60.1%) contrasta marcadamente con la mínima presencia hispana (0.3%), indicando una brecha crítica en la inclusión de esta comunidad.

Esta distribución desbalanceada sugiere que, a pesar de tener representación de seis grupos raciales diferentes, existen barreras potenciales en tus procesos de reclutamiento y retención que limitan la diversidad étnica real. El alto porcentaje de empleados que no especifican su origen hispano/latino (11.6%) también señala oportunidades para mejorar los sistemas de recolección de datos y fomentar un ambiente donde los colaboradores se sientan cómodos compartiendo esta información.

# **6. ¿Cuáles son las mejores fuentes de contratación si se quiere garantizar una organización diversa?**
"""

print("\n=== PREGUNTA 3: Mejores fuentes de contratación para diversidad ===")

# Pruebas Chi-cuadrado
contingency_race = pd.crosstab(df['RecruitmentSource'], df['RaceDesc'])
chi2_race, p_race, dof_race, expected_race = chi2_contingency(contingency_race)

contingency_gender = pd.crosstab(df['RecruitmentSource'], df['Sex'])
chi2_gender, p_gender, dof_gender, expected_gender = chi2_contingency(contingency_gender)

contingency_hispanic = pd.crosstab(df['RecruitmentSource'], df['HispanicLatino'])
chi2_hispanic, p_hispanic, dof_hispanic, expected_hispanic = chi2_contingency(contingency_hispanic)

# GRÁFICAS SIMPLES
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# 1. DIVERSIDAD RACIAL - Total por fuente
contingency_race.sum(axis=1).plot(kind='bar', ax=axes[0], color='skyblue', alpha=0.8)
axes[0].set_title(f'Total Empleados por Fuente\nRaza: Chi²={chi2_race:.1f}, p={p_race:.4f}')
axes[0].set_ylabel('Número de Empleados')
axes[0].tick_params(axis='x', rotation=45)

# 2. GÉNERO - Diferencia entre M y F
diferencia_genero = contingency_gender['M'] - contingency_gender['F']
diferencia_genero.plot(kind='bar', ax=axes[1], color='lightcoral', alpha=0.8)
axes[1].set_title(f'Diferencia Género (M-F)\nChi²={chi2_gender:.1f}, p={p_gender:.4f}')
axes[1].set_ylabel('Diferencia (M - F)')
axes[1].tick_params(axis='x', rotation=45)

# 3. HISPANIC/LATINO - Porcentaje Sí
porcentaje_hispanic = (contingency_hispanic['Sí'] / contingency_hispanic.sum(axis=1)) * 100
porcentaje_hispanic.plot(kind='bar', ax=axes[2], color='lightgreen', alpha=0.8)
axes[2].set_title(f'% Hispanic/Latino por Fuente\nChi²={chi2_hispanic:.1f}, p={p_hispanic:.4f}')
axes[2].set_ylabel('Porcentaje (%)')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# RESUMEN
print(f"\n📊 RESUMEN ESTADÍSTICO:")
print(f"p: {p_race}")
print(f"Raza: {'✅ SIGNIFICATIVA' if p_race < 0.05 else '❌ NO significativa'}")
print(f"p: {p_gender}")
print(f"Género: {'✅ SIGNIFICATIVA' if p_gender < 0.05 else '❌ NO significativa'}")
print(f"p: {p_hispanic}")
print(f"Hispano/Latino: {'✅ SIGNIFICATIVA' if p_hispanic < 0.05 else '❌ NO significativa'}")

"""Los resultados estadísticos revelan patrones diferenciados en la efectividad de las fuentes de reclutamiento para atraer diversidad. Existe una relación altamente significativa entre las fuentes de contratación y la diversidad racial (p = 2.5e-08), lo que indica que ciertas fuentes son notablemente más efectivas para atraer candidatos de diferentes grupos étnicos. Este hallazgo es crucial para diseñar estrategias de reclutamiento enfocadas en mejorar la representación racial identificada como deficiente en el análisis anterior.

Por el contrario, no se encontraron relaciones significativas entre las fuentes de contratación y el balance de género (p = 0.161) ni con la representación hispana/latina (p = 0.154). Esto sugiere que el género y el origen hispano/latino se distribuyen de manera similar across todas las fuentes de reclutamiento, por lo que estas variables no deberían ser factores determinantes al seleccionar fuentes de contratación específicas.

Estrategia recomendada: Para abordar las brechas de diversidad identificadas previamente, especialmente la subrepresentación hispana y el desbalance racial, se deben priorizar aquellas fuentes de reclutamiento que han demostrado ser estadísticamente efectivas para atraer diversidad racial, mientras se desarrollan estrategias adicionales específicas para atraer talento hispano, dado que las fuentes actuales no muestran diferenciación en este aspecto.

# **7. ¿Se puede predecir quién va a dejar la empresa y quién no? ¿Qué nivel de precisión se puede alcanzar en este aspecto?**
"""

import seaborn as sns
import matplotlib.pyplot as plt


print("=== PREGUNTA 4: ¿Se puede predecir quién va a dejar la empresa y quién no?===")
print("     === ¿Qué nivel de precisión se puede alcanzar en este aspecto?===")


# Crear columna IsActive basada en TermReason
df['IsActive'] = df['TermReason'] == 'N/A-StillEmployed'

if {'Department', 'IsActive'}.issubset(df.columns):

    # 1. Crosstab normalizado por fila (%)
    rot_tab = pd.crosstab(df['Department'], df['IsActive'], normalize='index') * 100
    rot_tab = rot_tab.rename(columns={True: 'Activos', False: 'Terminados'})

    # Ordenar por % de terminados (mayor a menor)
    rot_tab_sorted = rot_tab.sort_values('Terminados', ascending=False)

    # Dividir en 2 grupos: mayor rotación (top 50%) y menor rotación (bottom 50%)
    mid_index = len(rot_tab_sorted) // 2
    high_rot = rot_tab_sorted.iloc[:mid_index]
    low_rot = rot_tab_sorted.iloc[mid_index:]

    # Mostrar tablas
    print("\n--- Departamentos con MAYOR rotación ---")
    print(high_rot.round(2))

    print("\n--- Departamentos con MENOR rotación ---")
    print(low_rot.round(2))

    # 2. Heatmaps separados
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # Heatmap para alta rotación
    sns.heatmap(high_rot, annot=True, fmt=".1f", cmap="Reds",
                cbar_kws={'label': '% empleados'}, ax=ax1)
    ax1.set_title("Departamentos con MAYOR Rotación")
    ax1.set_ylabel("Departamento")
    ax1.set_xlabel("Estado Laboral")

    # Heatmap para baja rotación
    sns.heatmap(low_rot, annot=True, fmt=".1f", cmap="Blues",
                cbar_kws={'label': '% empleados'}, ax=ax2)
    ax2.set_title("Departamentos con MENOR Rotación")
    ax2.set_ylabel("Departamento")
    ax2.set_xlabel("Estado Laboral")

    plt.tight_layout()
    plt.show()

    # 3. Análisis detallado de razones de terminación por departamento
    print("\n" + "="*50)
    print("ANÁLISIS DETALLADO DE RAZONES DE TERMINACIÓN POR DEPARTAMENTO")
    print("="*50)

    # Filtrar solo empleados terminados (excluir activos)
    empleados_terminados = df[df['TermReason'] != 'N/A-StillEmployed']

    if len(empleados_terminados) > 0:
        # Crear tabla cruzada de departamento vs razón de terminación
        razones_por_depto = pd.crosstab(empleados_terminados['Department'],
                                       empleados_terminados['TermReason'])

        # Calcular porcentajes por departamento
        razones_por_depto_pct = razones_por_depto.div(razones_por_depto.sum(axis=1), axis=0) * 100

        print("\nRazones de terminación por departamento (%):")
        print(razones_por_depto_pct.round(1))

        # 4. Heatmap de razones de terminación
        plt.figure(figsize=(12, 8))
        sns.heatmap(razones_por_depto_pct, annot=True, fmt=".1f", cmap="YlOrRd",
                   cbar_kws={'label': '% de terminaciones por departamento'})
        plt.title("Distribución de Razones de Terminación por Departamento")
        plt.ylabel("Departamento")
        plt.xlabel("Razón de Terminación")
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.show()

    else:
        print("No hay empleados terminados para analizar.")

else:
    print("Columnas necesarias no encontradas en el dataset.")

# 5. Resumen ejecutivo
print("\n" + "="*50)
print("RESUMEN EJECUTIVO - ROTACIÓN POR DEPARTAMENTO")
print("="*50)

if {'Department', 'IsActive'}.issubset(df.columns):
    total_por_depto = df['Department'].value_counts()
    terminados_por_depto = df[df['IsActive'] == False]['Department'].value_counts()

    print("\nTasa de rotación por departamento:")
    print("-" * 40)

    for depto in rot_tab_sorted.index:
        tasa_rotacion = rot_tab_sorted.loc[depto, 'Terminados']
        total_empleados = total_por_depto.get(depto, 0)
        total_terminados = terminados_por_depto.get(depto, 0)

        print(f"{depto}:")
        print(f"  • Tasa de rotación: {tasa_rotacion:.1f}%")
        print(f"  • Empleados totales: {total_empleados}")
        print(f"  • Empleados terminados: {total_terminados}")

        # Mostrar razones principales si hay terminados
        if total_terminados > 0:
            razones_depto = empleados_terminados[empleados_terminados['Department'] == depto]['TermReason'].value_counts()
            if len(razones_depto) > 0:
                razon_principal = razones_depto.index[0]
                print(f"  • Razón principal: {razon_principal}")
        print()

"""El análisis revela patrones claros de rotación que permiten predecir qué empleados tienen mayor probabilidad de dejar la empresa, con un nivel de precisión significativo basado en factores departamentales y causas específicas. La rotación varía dramáticamente por departamento, desde el 100% en Executive Office hasta el 22% en IT/IS, indicando que la pertenencia departamental es un predictor fuerte. Además, las razones de terminación muestran patrones predecibles: "Another position" es la causa principal en Production (20.5%) y Sales (20.0%), mientras que problemas de asistencia y desempeño dominan en Software Engineering (25%) e IT/IS (20%).

Estos patrones consistentes sugieren que se puede desarrollar un modelo predictivo con alta precisión utilizando variables como departamento, historial de asistencia, y desempeño laboral. La concentración de causas específicas por área funcional permite crear algoritmos segmentados que identifiquen empleados en riesgo basándose en su perfil departamental y conductas laborales observables, ofreciendo oportunidades intervenciones preventivas dirigidas.

# **8. ¿Hay áreas de la empresa en las que la remuneración no es equitativa?**
"""

print("\n=== PREGUNTA 5: ¿Hay áreas con remuneración no equitativa? ===")

from scipy.stats import f_oneway
from scipy.stats import kruskal
from scipy.stats import ttest_ind # Importar ttest_ind

# 1. EQUIDAD POR GÉNERO - Prueba t para salarios
print("📊 EQUIDAD POR GÉNERO:")
salarios_hombres = df[df['Sex'] == 'M']['Salary'].dropna()
salarios_mujeres = df[df['Sex'] == 'F']['Salary'].dropna()

t_stat, p_gender = ttest_ind(salarios_hombres, salarios_mujeres)
print(f"Prueba t: t = {t_stat:.3f}, p = {p_gender:.4f}")

if p_gender < 0.05:
    print(f"✅ DIFERENCIA SIGNIFICATIVA: Hombres (${salarios_hombres.mean():.0f}) vs Mujeres (${salarios_mujeres.mean():.0f})")
else:
    print("❌ No hay diferencia significativa por género")

# 2. EQUIDAD POR RAZA - ANOVA
print(f"\n📊 EQUIDAD POR RAZA:")
grupos_raza = [df[df['RaceDesc'] == raza]['Salary'].dropna() for raza in df['RaceDesc'].unique()]
f_stat, p_race = f_oneway(*grupos_raza)
print(f"ANOVA: F = {f_stat:.3f}, p = {p_race:.4f}")

if p_race < 0.05:
    print("✅ DIFERENCIA SIGNIFICATIVA entre razas")
    # Mostrar promedios por raza
    for raza in df['RaceDesc'].unique():
        salario_promedio = df[df['RaceDesc'] == raza]['Salary'].mean()
        print(f"   {raza}: ${salario_promedio:.0f}")
else:
    print("❌ No hay diferencia significativa por raza")

# 3. EQUIDAD POR HISPANIC/LATINO - Prueba t
print(f"\n📊 EQUIDAD POR ORIGEN HISPANO/LATINO:")
salarios_si = df[df['HispanicLatino'] == 'Sí']['Salary'].dropna()
salarios_no = df[df['HispanicLatino'] == 'No']['Salary'].dropna()

t_stat_hisp, p_hisp = ttest_ind(salarios_si, salarios_no)
print(f"Prueba t: t = {t_stat_hisp:.3f}, p = {p_hisp:.4f}")

if p_hisp < 0.05:
    print(f"✅ DIFERENCIA SIGNIFICATIVA: Sí (${salarios_si.mean():.0f}) vs No (${salarios_no.mean():.0f})")
else:
    print("❌ No hay diferencia significativa por origen hispano/latino")

# GRÁFICAS SIMPLES
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# 1. Salarios por género
df.boxplot(column='Salary', by='Sex', ax=axes[0])
axes[0].set_title(f'Salarios por Género\np-value = {p_gender:.4f}')
axes[0].set_ylabel('Salario ($)')

# 2. Salarios por raza
df.boxplot(column='Salary', by='RaceDesc', ax=axes[1], rot=45)
axes[1].set_title(f'Salarios por Raza\np-value = {p_race:.4f}')
axes[1].set_ylabel('Salario ($)')

# 3. Salarios por hispanic/latino
df.boxplot(column='Salary', by='HispanicLatino', ax=axes[2])
axes[2].set_title(f'Salarios por Hispanic/Latino\np-value = {p_hisp:.4f}')
axes[2].set_ylabel('Salario ($)')

plt.suptitle('')
plt.tight_layout()
plt.show()

# RESUMEN FINAL
print(f"\n🎯 RESUMEN DE EQUIDAD SALARIAL:")
print(f"Género: {'❌ PROBLEMA' if p_gender < 0.05 else '✅ EQUITATIVO'}")
print(f"Raza: {'❌ PROBLEMA' if p_race < 0.05 else '✅ EQUITATIVO'}")
print(f"Hispano/Latino: {'❌ PROBLEMA' if p_hisp < 0.05 else '✅ EQUITATIVO'}")

"""Los resultados estadísticos y el análisis visual indican que no se observan diferencias salariales significativas entre los distintos grupos demográficos evaluados.

En cuanto a la equidad por género, la prueba t (t = 1.042, p = 0.2982) demuestra que no existe evidencia estadística suficiente para afirmar que hay diferencias salariales entre hombres y mujeres. Las distribuciones salariales de ambos grupos presentan medianas similares y rangos que se superponen considerablemente.

Respecto a la equidad por raza, el análisis ANOVA (F = 1.180, p = 0.3187) revela que las variaciones salariales entre los seis grupos raciales representados no son estadísticamente significativas. Visualmente, aunque se observan algunas diferencias en los rangos salariales, las distribuciones se superponen sin que ningún grupo aparezca claramente favorecido.

Finalmente, en la equidad por origen hispano/latino, la prueba t (t = 1.026, p = 0.3058) confirma la ausencia de diferencias significativas, reflejándose en distribuciones salariales consistentes entre los grupos identificados como hispanos/latinos y no hispanos.

En conjunto, los análisis estadísticos y las representaciones gráficas convergen en indicar que las prácticas remunerativas en la organización mantienen estándares de equidad en función del género, raza y origen étnico de los empleados.
"""